<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StudyTaskManager.Core\StudyTaskManager.Core.csproj" />
    <ProjectReference Include="..\StudyTaskManager.Validation\StudyTaskManager.Validation.csproj" />
  </ItemGroup>

</Project>
